#!/usr/bin/env python3
"""Generate a deterministic compile-time GEMM dispatch policy from CSV data.

The selector never opens the SQLite database. It accepts one (arch, dtype)
CSV, filters failed/incomplete rows, and selects a candidate only when it is
at least ``threshold`` faster than the fallback at the same square size.

Example:
    python scripts/select_kernel.py results/candidates.csv \
        --output build/generated/k1_policy.h --label k1-baseline
"""

from __future__ import annotations

import argparse
import csv
import math
import sys
from pathlib import Path

DEFAULT_SIZES = (32, 64, 96, 128, 192, 256, 384, 512, 768, 1024, 1536, 2048, 3072, 4096)
CANDIDATE_TILES = {
    "k1_t": (64, 64, 16),
    "k1_t_32x64x16": (32, 64, 16),
    "k1_t_64x32x16": (64, 32, 16),
    "k1_t_64x64x8": (64, 64, 8),
}


def finite(row: dict[str, str], field: str) -> float | None:
    try:
        value = float(row.get(field, ""))
    except ValueError:
        return None
    return value if math.isfinite(value) and value > 0.0 else None


def valid(row: dict[str, str], tolerance: float) -> bool:
    median = finite(row, "kernel_median_ns")
    if median is None:
        return False
    try:
        rel = float(row.get("max_rel_err", ""))
    except ValueError:
        return False
    if not math.isfinite(rel) or rel < 0.0 or rel > tolerance:
        return False
    # These are stability/tie-break fields, not the selection metric.
    return all(
        finite(row, field) is not None
        for field in (
            "kernel_p95_ns",
            "kernel_std_ns",
            "kernel_ci_low_ns",
            "kernel_ci_high_ns",
        )
    )


def cpp_candidate(name: str) -> str | None:
    tile = CANDIDATE_TILES.get(name)
    if tile is None:
        return None
    return f"k1_t<{tile[0]}, {tile[1]}, {tile[2]}>"


def read_rows(path: Path) -> tuple[str, str, list[dict[str, str]]]:
    with path.open(newline="") as stream:
        rows = list(csv.DictReader(stream))
    if not rows:
        raise ValueError("CSV contains no rows")
    pairs = {(row.get("arch", ""), row.get("dtype", "")) for row in rows}
    if len(pairs) != 1 or "" in next(iter(pairs)):
        raise ValueError("CSV must contain exactly one non-empty (arch, dtype) pair")
    arch, dtype = next(iter(pairs))
    return arch, dtype, rows


def choose(
    rows: list[dict[str, str]],
    sizes: tuple[int, ...],
    fallback: str,
    threshold: float,
    tolerance: float,
    prefix: str,
) -> dict[int, str]:
    by_n: dict[int, list[dict[str, str]]] = {}
    for row in rows:
        try:
            n = int(row.get("N", ""))
        except ValueError:
            continue
        if n in sizes:
            by_n.setdefault(n, []).append(row)

    policy: dict[int, str] = {}
    for n in sizes:
        candidates = [
            row
            for row in by_n.get(n, [])
            if row.get("kernel_name", "").startswith(prefix)
            and cpp_candidate(row.get("kernel_name", "")) is not None
            and valid(row, tolerance)
        ]
        fallback_rows = [
            row
            for row in by_n.get(n, [])
            if row.get("kernel_name") == fallback and valid(row, tolerance)
        ]
        fallback_median = (
            finite(fallback_rows[0], "kernel_median_ns") if fallback_rows else None
        )
        if fallback_median is None:
            policy[n] = fallback
            continue

        eligible = [
            row
            for row in candidates
            if (finite(row, "kernel_median_ns") or math.inf)
            <= fallback_median * (1.0 - threshold)
        ]
        eligible.sort(
            key=lambda row: (
                finite(row, "kernel_median_ns") or math.inf,
                finite(row, "kernel_p95_ns") or math.inf,
                finite(row, "kernel_std_ns") or math.inf,
                (finite(row, "kernel_ci_high_ns") or math.inf)
                - (finite(row, "kernel_ci_low_ns") or math.inf),
                row["kernel_name"],
            )
        )
        policy[n] = eligible[0]["kernel_name"] if eligible else fallback
    return policy


def emit(
    path: Path,
    arch: str,
    dtype: str,
    source: str,
    policy: dict[int, str],
    fallback: str,
    threshold: float,
    tolerance: float,
    label: str,
) -> None:
    if arch != "sm_120" or dtype != "bf16":
        raise ValueError("generated k1_dispatch currently supports only sm_120/bf16")
    fallback_cpp = "k1_smem" if fallback == "k1_smem" else None
    if fallback_cpp is None:
        raise ValueError("only k1_smem is a supported generated fallback")
    lines = [
        "// Generated by scripts/select_kernel.py; do not edit.",
        f"// source={source}",
        f"// label={label}",
        f"// arch={arch} dtype={dtype} metric=kernel_median_ns threshold={threshold:.6g}",
        f"// fallback={fallback} accuracy_tolerance={tolerance:.6g}",
        '#include "sm120/gemm_bf16.cuh"',
        "",
        "namespace gemm_y {",
        "struct k1_dispatch {",
        '  static constexpr std::string_view name() { return "k1_dispatch"; }',
        "  static constexpr std::string_view selected_kernel_name(int n) {",
        "    switch (n) {",
    ]
    for n, name in policy.items():
        lines.append(f'      case {n}: return "{name}";')
    lines += [
        f'      default: return "{fallback}";',
        "    }",
        "  }",
        "  static constexpr std::string_view description() {",
        '    return "offline switch dispatch; fallback k1_smem";',
        "  }",
        "  void operator()(GemmArgs<__nv_bfloat16> args, cudaStream_t stream) const {",
        "    switch (args.C.cols) {",
    ]
    for n, name in policy.items():
        candidate = cpp_candidate(name)
        if candidate is None:
            lines.append(f"      case {n}: {fallback_cpp}{{}}(args, stream); return;")
        else:
            lines.append(f"      case {n}: {candidate}{{}}(args, stream); return;")
    lines += [
        f"      default: {fallback_cpp}{{}}(args, stream); return;",
        "    }",
        "  }",
        "};",
        "}  // namespace gemm_y",
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("csv", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--fallback", default="k1_smem")
    parser.add_argument("--threshold", type=float, default=0.02)
    parser.add_argument("--tolerance", type=float, default=1e-2)
    parser.add_argument("--prefix", default="k1_t")
    parser.add_argument("--label", default="")
    parser.add_argument("--sizes", type=int, nargs="+", default=list(DEFAULT_SIZES))
    args = parser.parse_args()
    if not 0.0 <= args.threshold < 1.0:
        parser.error("--threshold must be in [0, 1)")
    try:
        arch, dtype, rows = read_rows(args.csv)
        policy = choose(
            rows,
            tuple(args.sizes),
            args.fallback,
            args.threshold,
            args.tolerance,
            args.prefix,
        )
        emit(
            args.output,
            arch,
            dtype,
            str(args.csv),
            policy,
            args.fallback,
            args.threshold,
            args.tolerance,
            args.label,
        )
    except (OSError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    for n in args.sizes:
        print(f"{arch},{dtype},N={n},{policy[n]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
